on:
  push:
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v2
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
      - name: Install Deps
        run: sudo apt-get install -y python3
      - name: Install Shards
        run: shards install
      - name: Install Python reqs
        run: make install_deps
      - name: Generate test data
        run: make generate_testdata
      - name: Run tests
        run: crystal spec
